# Upload method config for NUCLEO_F412ZG.
# Mirrors NUCLEO_F446RE structure; STM32CUBE is the project default.

set(UPLOAD_METHOD_DEFAULT MBED)

# MBED
set(MBED_UPLOAD_ENABLED TRUE)
set(MBED_RESET_BAUDRATE 115200)

# JLINK
set(JLINK_UPLOAD_ENABLED TRUE)
set(JLINK_CPU_NAME STM32F412ZG)
set(JLINK_CLOCK_SPEED 4000)
set(JLINK_UPLOAD_INTERFACE SWD)

# STM32Cube
set(STM32CUBE_UPLOAD_ENABLED TRUE)
set(STM32CUBE_CONNECT_COMMAND -c port=SWD reset=HWrst)
set(STM32CUBE_GDBSERVER_ARGS --swd)
